[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/directions"
  to = "/.netlify/functions/directions"
  status = 200
